version: "3.7" 
networks:
  didacto-event-network:
    driver: bridge
services:
  didacto-event-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5004:5004
    environment:
      - REDIS_HOST=didacto-event-redis
      - REDIS_PORT=6379
    depends_on:
      - didacto-event-redis
    networks:
      - didacto-event-network
  didacto-event-redis:
    image: redis:7.0.15-alpine
    container_name: didacto-event-redis
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 6391:6379
    volumes: 
      - ./volumes/redis/data:/data
      - ./volumes/redis/conf:/usr/local/etc/redis/redis.conf
    networks:
      - didacto-event-network